services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  redis:
    image: redis:alpine
    restart: unless-stopped

  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-router.entrypoints=web"
      - "traefik.http.routers.server-router.rule=PathPrefix(`/`)"
      - "traefik.http.services.server-service.loadbalancer.server.port=8000"

  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    ports:
      - 4321:4321
    depends_on:
      - server

  k6-tests:
    build: k6-tests
    entrypoint: /bin/true
    volumes:
      - ./k6-tests/tests:/tests
    depends_on:
      - client
