services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - project.env

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./lgtm-data:/data

  flyway:
    image: flyway/flyway:10.8.1-alpine
    environment:
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
    volumes:
      - ./database-migrations:/flyway/sql
    depends_on:
      - database
    command: -connectRetries=60 migrate
    env_file:
      - project.env

  load-balancer:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  client:
    build: ./client
    environment:
      OTEL_SERVICE_NAME: client
    env_file:
      - project.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"

  inference-api:
    build: ./inference-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inference-api.rule=PathPrefix(`/inference-api`)"
      - "traefik.http.services.inference-api.loadbalancer.server.port=8000"

  server:
    build: ./server
    environment:
      OTEL_SERVICE_NAME: server
      POSTGRES_HOST: database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=8000"

  grader:
    build: ./grader
    restart: on-failure
    environment:
      OTEL_SERVICE_NAME: grader
      POSTGRES_HOST: database
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grader-api.rule=PathPrefix(`/grader-api`)"
      - "traefik.http.routers.grader-api.middlewares=grader-api-replacepath"
      - "traefik.http.middlewares.grader-api-replacepath.replacePathRegex.regex=^/grader-api(.*)"
      - "traefik.http.middlewares.grader-api-replacepath.replacePathRegex.replacement=/api$$1"
      - "traefik.http.services.grader-api.loadbalancer.server.port=8000"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
